<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "documents".
 *
 * @property integer $id
 * @property string $name
 * @property string $path
 * @property string $money_url
 * @property string $original_url
 * @property string $preview
 * @property string $description
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $subject
 * @property integer $user
 * @property integer $status
 * @property string $aliasModel
 */
abstract class Documents extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'documents';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['path', 'money_url', 'original_url', 'preview', 'description'], 'string'],
            [['created_at', 'updated_at', 'subject', 'user', 'status'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'path' => 'Path',
            'money_url' => 'Money Url',
            'original_url' => 'Original Url',
            'preview' => 'Preview',
            'description' => 'Description',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'subject' => 'Subject',
            'user' => 'User',
            'status' => 'Status',
        ];
    }




}
