<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "news".
 *
 * @property integer $id
 * @property string $content
 * @property string $tag
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $number_upload
 * @property string $aliasModel
 */
abstract class News extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['content', 'tag'], 'string'],
            [['created_at', 'updated_at', 'number_upload'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'content' => 'Content',
            'tag' => 'Tag',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'number_upload' => 'Number Upload',
        ];
    }




}
