<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "program".
 *
 * @property integer $id
 * @property integer $department_id
 * @property string $semester
 * @property integer $subject
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Program extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'program';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['department_id', 'subject', 'created_at', 'updated_at'], 'integer'],
            [['semester'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'department_id' => 'Department ID',
            'semester' => 'Semester',
            'subject' => 'Subject',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }




}
