<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tbl_subject".
 *
 * @property integer $subject_id
 * @property string $subject_name
 * @property string $subject_code
 * @property string $subject_active
 * @property string $subject_university
 * @property integer $subject_type
 * @property integer $subject_year
 * @property integer $subject_credits
 * @property string $subject_credit_hour
 * @property string $subject_requirement
 * @property string $subject_target
 * @property string $subject_info
 * @property string $subject_test
 * @property integer $subject_faculty
 * @property integer $subject_dept
 * @property string $subject_content
 * @property integer $subject_general_faculty_id
 * @property string $aliasModel
 */
abstract class TblSubject extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_subject';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['subject_type', 'subject_year', 'subject_credits', 'subject_faculty', 'subject_dept', 'subject_general_faculty_id'], 'integer'],
            [['subject_content'], 'string'],
            [['subject_name', 'subject_credit_hour'], 'string', 'max' => 100],
            [['subject_code', 'subject_active', 'subject_university'], 'string', 'max' => 45],
            [['subject_requirement'], 'string', 'max' => 500],
            [['subject_target'], 'string', 'max' => 3000],
            [['subject_info', 'subject_test'], 'string', 'max' => 1000]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'subject_id' => 'Subject ID',
            'subject_name' => 'Subject Name',
            'subject_code' => 'Subject Code',
            'subject_active' => 'Subject Active',
            'subject_university' => 'Subject University',
            'subject_type' => 'Subject Type',
            'subject_year' => 'Subject Year',
            'subject_credits' => 'Subject Credits',
            'subject_credit_hour' => 'Subject Credit Hour',
            'subject_requirement' => 'Subject Requirement',
            'subject_target' => 'Subject Target',
            'subject_info' => 'Subject Info',
            'subject_test' => 'Subject Test',
            'subject_faculty' => 'Subject Faculty',
            'subject_dept' => 'Subject Dept',
            'subject_content' => 'Subject Content',
            'subject_general_faculty_id' => 'Subject General Faculty ID',
        ];
    }




}
