<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tbl_teacher".
 *
 * @property integer $teacher_id
 * @property string $teacher_name
 * @property string $teacher_personal_page
 * @property string $teacher_avatar
 * @property string $teacher_description
 * @property string $teacher_work_place
 * @property integer $teacher_active
 * @property string $teacher_acadamic_title
 * @property string $teacher_birthday
 * @property integer $teacher_sex
 * @property integer $teacher_faculty
 * @property integer $teacher_dept
 * @property double $teacher_rate
 * @property string $teacher_personality
 * @property string $advices
 * @property string $teacher_research
 * @property string $teacher_phone
 * @property string $teacher_email
 * @property string $aliasModel
 */
abstract class TblTeacher extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tbl_teacher';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['teacher_active', 'teacher_sex', 'teacher_faculty', 'teacher_dept'], 'integer'],
            [['teacher_rate'], 'number'],
            [['teacher_phone', 'teacher_email'], 'required'],
            [['teacher_name', 'teacher_acadamic_title', 'teacher_birthday'], 'string', 'max' => 45],
            [['teacher_personal_page', 'teacher_avatar'], 'string', 'max' => 200],
            [['teacher_description', 'teacher_personality', 'advices', 'teacher_research'], 'string', 'max' => 3000],
            [['teacher_work_place'], 'string', 'max' => 100],
            [['teacher_phone', 'teacher_email'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'teacher_id' => 'Teacher ID',
            'teacher_name' => 'Teacher Name',
            'teacher_personal_page' => 'Teacher Personal Page',
            'teacher_avatar' => 'Teacher Avatar',
            'teacher_description' => 'Teacher Description',
            'teacher_work_place' => 'Teacher Work Place',
            'teacher_active' => 'Teacher Active',
            'teacher_acadamic_title' => 'Teacher Acadamic Title',
            'teacher_birthday' => 'Teacher Birthday',
            'teacher_sex' => 'Teacher Sex',
            'teacher_faculty' => 'Teacher Faculty',
            'teacher_dept' => 'Teacher Dept',
            'teacher_rate' => 'Teacher Rate',
            'teacher_personality' => 'Teacher Personality',
            'advices' => 'Advices',
            'teacher_research' => 'Teacher Research',
            'teacher_phone' => 'Teacher Phone',
            'teacher_email' => 'Teacher Email',
        ];
    }




}
