<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "teachers".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $avatar
 * @property string $email
 * @property string $phone
 * @property string $website
 * @property integer $created_at
 * @property integer $updated_at
 * @property double $stars
 * @property integer $number_rated
 * @property integer $department
 * @property integer $status
 * @property string $aliasModel
 */
abstract class Teachers extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'teachers';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description', 'avatar'], 'string'],
            [['created_at', 'updated_at', 'number_rated', 'department', 'status'], 'integer'],
            [['stars'], 'number'],
            [['name', 'email', 'phone', 'website'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'avatar' => 'Avatar',
            'email' => 'Email',
            'phone' => 'Phone',
            'website' => 'Website',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'stars' => 'Stars',
            'number_rated' => 'Number Rated',
            'department' => 'Department',
            'status' => 'Status',
        ];
    }




}
