<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "users".
 *
 * @property integer $id
 * @property string $name
 * @property string $avatar
 * @property string $fb_id
 * @property string $description
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $number_upload
 * @property integer $points
 * @property integer $role
 * @property integer $status
 * @property string $gender
 * @property string $dob
 * @property string $email
 * @property string $pdf
 * @property string $aliasModel
 */
abstract class Users extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['avatar', 'description', 'pdf'], 'string'],
            [['created_at', 'updated_at', 'number_upload', 'points', 'role', 'status'], 'integer'],
            [['name', 'fb_id', 'gender', 'dob', 'email'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'avatar' => 'Avatar',
            'fb_id' => 'Fb ID',
            'description' => 'Description',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'number_upload' => 'Number Upload',
            'points' => 'Points',
            'role' => 'Role',
            'status' => 'Status',
            'gender' => 'Gender',
            'dob' => 'Dob',
            'email' => 'Email',
            'pdf' => 'Pdf',
        ];
    }




}
